version: "3.9"

services:
  proxy:
    build: ./proxy
    restart: always
    ports:
      - 3050:80
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - api
      - web

  db:
    image: mongo:4.4.6
    command: mongod --auth
    restart: unless-stopped
    environment:
      MONGO_USER_USERNAME: "${MONGO_USER_USERNAME}"
      MONGO_USER_PASSWORD: "${MONGO_USER_PASSWORD}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
      MONGO_DATABASE_DEV: "${MONGO_DATABASE_DEV}"
      MONGO_DATABASE_TEST: "${MONGO_DATABASE_TEST}"
    volumes:
      - db_data:/data/db
      - ./backend/app/db/entrypoint:/docker-entrypoint-initdb.d
    expose:
      - 27017
    networks:
      - backend
    logging:
      driver: none

  api:
    build: ./backend
    environment:
      MONGO_URI: "${MONGO_URI}"
      MONGO_USER_USERNAME: "${MONGO_USER_USERNAME}"
      MONGO_USER_PASSWORD: "${MONGO_USER_PASSWORD}"
      MONGO_DATABASE_DEV: "${MONGO_DATABASE_DEV}"
      MONGO_DATABASE_TEST: "${MONGO_DATABASE_TEST}"
      JWT_SECRET: "${JWT_SECRET}"
      JWT_EXPIRE: "${JWT_EXPIRE}"
    volumes:
      - /app/node_modules
      - ./backend:/app
      - /co3fs:/co3fs:ro

    expose:
      - 5000
    networks:
      - backend

  web:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    expose:
      - 3000
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db_data:
    driver: local
