// Auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADED = "USER_LOADED";
export const LOGOUT = "LOGOUT";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const CLEAR_ERROR = "CLEAR_ERROR";

// Project
export const CREATE_PROJECT = "CREATE_PROJECT";
export const GET_PROJECTS = "GET_PROJECTS";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const SET_SELECTED_PROJECT = "SET_SELECTED_PROJECT";
export const CLEAR_SELECTED_PROJECT = "CLEAR_SELECTED_PROJECT";
export const SET_PROJECT_ERROR = "SET_PROJECT_ERROR";
export const CLEAR_PROJECT_ERROR = "CLEAR_PROJECT_ERROR";
export const SET_PROJECT_LOADING = "SET_PROJECT_LOADING";

// Alert
export const SET_ALERT = "SET_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

// URL
export const SET_URL = "SET_URL";
export const CLEAR_URL = "CLEAR_URL";

// Watch Directory
export const GET_WATCH_DIRS = "GET_WATCH_DIRS";
export const CREATE_WATCH_DIR = "CREATE_WATCH_DIR";
export const UPDATE_WATCH_DIRS = "UPDATE_WATCH_DIRS";
export const DELETE_WATCH_DIR = "DELETE_WATCH_DIR";
export const SET_WATCH_DIRS_LOADING = "SET_WATCH_DIRS_LOADING";
export const SET_WATCH_DIRS_ERROR = "SET_WATCH_DIRS_ERROR";
export const CLEAR_WATCH_DIRS = "CLEAR_WATCH_DIRS";
